name = "Spooky Scary Modpack"
author = "ryleu,otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68da03d3560db939ba8f0257b3acc9e540ca14bf47fda56386457f8a85287c95"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
