name = "Spooky Scary Modpack"
author = "ryleu,otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9f09eb78dd83f5646272f2bfca5e4db690c19ee4f57dbcc6165252232ca0efa"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
