[[mods]]
name = "Alternate Current"
url = "https://cdn.modrinth.com/data/r0v8vy1s/versions/v9lKbHW6/alternate-current-mc1.19-1.7.0.jar"

[[mods]]
name = "AmbientSounds 5"

[[mods]]
name = "Architectury API (Fabric/Forge)"

[[mods]]
name = "Bunch O' Bugs"
url = "https://cdn.discordapp.com/attachments/1149078798726340739/1160815131211612230/bunchobugs-1.3.2-1.19.2.jar"

[[mods]]
name = "Canary"
url = "https://cdn.modrinth.com/data/qa2H4BS9/versions/FReV3YPW/canary-mc1.19.2-0.2.8.jar"

[[mods]]
name = "Chisels & Bits - For Forge"

[[mods]]
name = "Chunky"
url = "https://cdn.modrinth.com/data/fALzjamp/versions/WNen5Iom/Chunky-1.3.38.jar"

[[mods]]
name = "Connectedness"
url = "https://cdn.modrinth.com/data/ceiPqFmI/versions/r4SIDnDr/connectedness-2.0.1a.jar"

[[mods]]
name = "CorgiLib"
url = "https://cdn.modrinth.com/data/ziOp6EO8/versions/ja9yy4N9/CorgiLib-forge-1.19.2-1.0.0.34.jar"

[[mods]]
name = "CoroUtil"

[[mods]]
name = "CreativeCore"

[[mods]]
name = "Dungeons and Taverns"
url = "https://cdn.modrinth.com/data/tpehi7ww/versions/WfuA1Ai8/dungeons-and-taverns-2.0.2.jar"

[[mods]]
name = "EMI"
url = "https://cdn.modrinth.com/data/fRiHVvU7/versions/VldBzgSe/emi-1.0.22%2B1.19.2%2Bforge.jar"

[[mods]]
name = "EnhancedVisuals"
url = "https://cdn.modrinth.com/data/KjL0jE2w/versions/M60M1NWo/EnhancedVisuals_FORGE_v1.5.9_mc1.19.2.jar"

[[mods]]
name = "Entity Collision FPS Fix"
url = "https://cdn.modrinth.com/data/GiriLmaY/versions/1.0/Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0.jar"

[[mods]]
name = "[EMF] Entity Model Features"
url = "https://cdn.modrinth.com/data/4I1XuqiY/versions/KKMsC88r/entity_model_features_forge_1.19.2-1.0.2.jar"

[[mods]]
name = "Entity Culling"
url = "https://cdn.modrinth.com/data/NNAgCjsB/versions/WR6z6MYC/entityculling-forge-1.6.1-mc1.19.2.jar"

[[mods]]
name = "[ETF] Entity Texture Features"
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/tHwXqOG3/entity_texture_features_forge_1.19.2-4.5.1.jar"

[[mods]]
name = "Fastload"
url = "https://cdn.modrinth.com/data/kCpssoSb/versions/nHeyxX0A/Fastload-Reforged-mc1.19.2-3.4.0.jar"

[[mods]]
name = "FerriteCore"
url = "https://cdn.modrinth.com/data/uXXizFIs/versions/CtXsUUz6/ferritecore-5.0.3-forge.jar"

[[mods]]
name = "Fog Looks Good Now"
url = "https://cdn.modrinth.com/data/Bno70aWr/versions/uw4XHhfA/betterfog-1.19.2-1.1.2.jar"

[[mods]]
name = "From The Fog"
url = "https://cdn.modrinth.com/data/p1WH6sHr/versions/TZ33FEFm/From-The-Fog-1.19-v1.9.1-Forge-Fabric.jar"

[[mods]]
name = "Geckolib"
url = "https://cdn.modrinth.com/data/8BmcQJ2H/versions/lxzmD9V4/geckolib-forge-1.19-3.1.40.jar"

[[mods]]
name = "Global Packs"
url = "https://cdn.modrinth.com/data/NRLPy2mk/versions/BVJe6xwO/global_packs-forge-1.19.2-1.14.5_forge.jar"

[[mods]]
name = "Hourglass"
url = "https://cdn.modrinth.com/data/1ZqmoFFP/versions/ZMHn5FFd/hourglass-1.19.1-1.2.1.1.jar"

[[mods]]
name = "Just Zoom"
url = "https://cdn.modrinth.com/data/iAiqcykM/versions/G2VLRt4r/justzoom_forge_1.0.1-1_MC_1.19.jar"

[[mods]]
name = "Konkrete"
url = "https://cdn.modrinth.com/data/J81TRJWm/versions/a4UZ7nGe/konkrete_forge_1.6.1_MC_1.19-1.19.2.jar"

[[mods]]
name = "Lightspeed"
url = "https://cdn.modrinth.com/data/US93mifm/versions/fZzwk293/lightspeed-1.19.2-1.0.5.jar"

[[mods]]
name = "Let Me Despawn"
url = "https://cdn.modrinth.com/data/vE2FN5qn/versions/wiNkX0Xr/letmedespawn-1.18-forge-1.0.3.jar"

[[mods]]
name = "ManyIdeas Core"

[[mods]]
name = "ManyIdeas Halloween"

[[mods]]
name = "Memory Leak Fix"
url = "https://cdn.modrinth.com/data/NRjRiSSD/versions/AK7fR5Ja/memoryleakfix-forge-1.17%2B-1.1.2.jar"

[[mods]]
name = "Music Player"

[[mods]]
name = "No Chat Reports"
url = "https://cdn.modrinth.com/data/qQyHxfxd/versions/RNAG69Zu/NoChatReports-FORGE-1.19.2-v1.5.1.jar"

[[mods]]
name = "Nyf's Spiders"
url = "https://cdn.modrinth.com/data/dOGM7ccu/versions/ur5d56Rq/spiderstpo-1.19.2-2.0.4.jar"

[[mods]]
name = "Oculus"
url = "https://cdn.modrinth.com/data/GchcoXML/versions/4lE9D01D/oculus-mc1.19.2-1.6.9.jar"

[[mods]]
name = "Pluto"
url = "https://cdn.modrinth.com/data/I2K4u1Q7/versions/7JnXMAAf/pluto-mc1.19.2-0.0.9.jar"

[[mods]]
name = "Realistic Torches"

[[mods]]
name = "Reforgium"
url = "https://cdn.modrinth.com/data/vmn85VI7/versions/OcW1M8PC/reforgium-1.0.12a.jar"

[[mods]]
name = "Rubidium"
url = "https://cdn.modrinth.com/data/4ZqxOvjD/versions/bmmEZ4mh/rubidium-mc1.19.2-0.6.2c.jar"

[[mods]]
name = "Serene Seasons"

[[mods]]
name = "Smooth Boot (Reloaded)"
url = "https://cdn.modrinth.com/data/z53V2L4P/versions/YXklcDpN/smoothboot%28reloaded%29-mc1.19.2-0.0.2.jar"

[[mods]]
name = "Sound Physics Remastered"
url = "https://cdn.modrinth.com/data/qyVF9oeo/versions/ouODHxQ8/soundphysics-forge-1.19.2-1.2.1.jar"

[[mods]]
name = "Spelunker's Charm II"
url = "https://cdn.modrinth.com/data/WKLy3h5B/versions/B48qx3Gb/SpelunkersCharm-3.2.1-1.19.2.jar"

[[mods]]
name = "Starlight (Forge)"
url = "https://cdn.modrinth.com/data/iRfIGC1s/versions/1.1.1%2B1.19/starlight-1.1.1%2Bforge.cf5b10b.jar"

[[mods]]
name = "Terralith"
url = "https://cdn.modrinth.com/data/8oi3bsk5/versions/UJtMNPNx/Terralith_1.19.3_v2.3.11.jar"

[[mods]]
name = "True Darkness"
url = "https://cdn.modrinth.com/data/Ja7zPEaN/versions/Jknh5xMh/darkness-forge-mc119-2.0.101.jar"

[[mods]]
name = "U Team Core"

[[mods]]
name = "Whisperwoods"

[[mods]]
name = "Y Is There AutoJump"
url = "https://cdn.modrinth.com/data/D3W7NSps/versions/k9OEShQn/yisthereautojump-forge-1.19.2-1.2.1.jar"

[[mods]]
name = "Yeetus Experimentus"
url = "https://cdn.modrinth.com/data/HaaH232J/versions/YnVV0O6w/yeetusexperimentus-1.0.1-build.2%2Bmc1.19.1.jar"

[[mods]]
name = "YUNG's API"
url = "https://cdn.modrinth.com/data/Ua7DFN59/versions/GNNfW5IV/YungsApi-1.19.2-Forge-3.8.9.jar"

[[mods]]
name = "YUNG's Better Mineshafts"
url = "https://cdn.modrinth.com/data/HjmxVlSr/versions/iUlejQ4i/YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar"

[[mods]]
name = "Zombie Awareness"

