name = "Spooky Scary Modpack"
author = "ryleu,otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "973b4815407d6301f781ab27bb8f801be33f783a738d8a38b51e8230a4b74ec9"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
