name = "Spooky Scary Modpack"
author = "ryleu,otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d7ebe4abea48e47820d7475811615708ecddcea90f29429811e24469a894b8b"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
