name = "Spooky Scary Modpack"
author = "ryleu,otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d85413b12566a70a50ffbb91ede9133e2eaf55c48ec1ca07b6b62fdbc8773fe7"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
