name = "Spooky Scary Modpack"
author = "ryleu,otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a258eddc90cbc0b25e391c7da765258daaf77ab1b2fc28980e79a82f9415ae7a"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
