name = "Spooky Scary Modpack"
author = "ryleu,otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3483acd8369f2df4944071fe335c319bf14b46afaf8fe0fcdec2e712239fbbfe"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
